name: Update deps.json

on:
  push:
    paths:
      - "gradle/libs.versions.toml"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "**/build.gradle.kts"

  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      USE_BWRAP: "0"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deps.json
        run: |
          $(nix build .#packages.x86_64-linux.default.mitmCache.updateScript --print-out-paths)

      - name: Commit updated deps.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deps.json
          git diff --cached --quiet || git commit -m "chore: update deps.json"
          git push
